### ISSUE TITLE
Cannot find : vg_300d_skipgram_rel

### ISSUE THREAD

**Issue by jpeyre** [facebookresearch/Large-Scale-VRD#2]
Hi,
Thank you for releasing this code. 
I downloaded the pre-trained models as in README but didn't manage to find the pre-trained relco model : "vg_300d_skipgram_rel"
Where would it be possible to download it ? 
Thank you for your help !

**Comment by jz462** [comment]
@jpeyre Theoretically you won't need "vg_300d_skipgram_rel" since the cached ground-truth files are already provided in `$ROOT_DIR/datasets/cache/`, with a suffix of "_gt_roidb.pkl". As you can see from line 120 to 127 in `$ROOT_DIR/lib/vg_wiki_and_relco.py`, it will just load this cached file and return instead of looking for "vg_300d_skipgram_rel".

Anyway, you can download all necessary files [here](https://www.dropbox.com/s/r6uh5n9h76k41w7/Ji%20Zhang%20-%20embeddings.zip). Unzip it, and put those two folders in `$ROOT_DIR/datasets/large_scale_VRD/`. This should solve the problem.

**Comment by jz462** [comment]
> Hi,
> Thank you for releasing this code.
> I downloaded the pre-trained models as in README but didn't manage to find the pre-trained relco model : "vg_300d_skipgram_rel"
> Where would it be possible to download it ?
> Thank you for your help !

@jpeyre Theoretically you won't need "vg_300d_skipgram_rel" since the cached ground-truth files are already provided in `$ROOT_DIR/datasets/cache/`, with a suffix of "_gt_roidb.pkl". As you can see from line 120 to 127 in `$ROOT_DIR/lib/vg_wiki_and_relco.py`, it will just load this cached file and return instead of looking for "vg_300d_skipgram_rel".

Anyway, you can download all necessary files [here](https://www.dropbox.com/s/r6uh5n9h76k41w7/Ji%20Zhang%20-%20embeddings.zip). Unzip it, and put those two folders in `$ROOT_DIR/datasets/large_scale_VRD/`. This should solve your problem directly.

**Comment by jpeyre** [comment]
Thank you for providing the language models, this solves the problem!
